version: "3"
services:
    httpd:
        image: "httpd:2.4.41-alpine"
        container_name: "lamp_httpd"
        hostname: httpd
        working_dir: /app
        ports:
            - 8080:80
        volumes:
            - ./app:/app:rw
            - ./services/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro # apache 配置
            - ./services/httpd/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro # vhosts 相关配置
        links:
            - php:php
        networks:
            - lamp

    php:
        image: "crunchgeek/php-fpm:7.3-r6"
        container_name: "lamp_php"
        hostname: php
        working_dir: /app
        expose:
            - 9000
        # links:
        #   - mysql:mysql
        volumes:
            - ./app:/app:rw
            - ./services/composer/composer.phar:/usr/local/bin/composer:ro
            - ./services/composer/config.json:/root/.composer/config.json:ro
            - ./cache/composer:/root/.composer/cache:rw
        # command:
        #     - /bin/sh
        #     - -c
        #     - |
        #         sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
        #         tail -f /dev/null
        networks:
            - lamp

    #   mysql:
    #     image: 'mysql:5.7.28'
    #     container_name: 'lamp_mysql'
    #     hostname: mysql
    #     ports:
    #       - '3306:3306'
    #     environment:
    #       - MYSQL_ROOT_PASSWORD=root
    #     networks:
    #       - lamp

networks:
    lamp:
        driver: bridge
